### PR TITLE
Pytest plugin

### LINKED ISSUE #11: pytest plugin?
Hi,

Is there interest in a plugin for pytest, similar to the nose plugin? I volunteer to write a PR for it, otherwise I can do it in a separate project.

Cheers,

### PR DESCRIPTION
**Pull request by nicoddemus**
Fixes #11.

Created pytest plugin (including appropriate test for it in a separate directory of those that run under nose) and updated documentation.

I took the liberty of adding myself to `AUTHORS` if that's OK, as it is common practice for contributors.

### CODE REVIEW

**Comment by bazsi** [comment]
You should add your own copyright instead of BalaBit (or both if you derived code from BB code).

Thanks for the great contribution.

**Comment by herczy** [comment]
@bazsi That will require some modification to the copyright checking code.

@nicoddemus Thanks for the contribution!

**Comment by nicoddemus** [comment]
Hi, 

Can't I just kind of "donate" the code to the project and therefore use the same copyright notice? 

If that's not an option, would be OK to just change the top of the copyright notice to mention my name?

**Comment by herczy** [comment]
Ok, we'll fix the copyright notice later. Thanks for the great contribution again.

**Comment by nicoddemus** [comment]
No problem! Don't hesitate in contacting me if any maintenance is required. :smile:

Cheers,

**Pull request merged**
